name: Vale Linter
description: The unofficial GitHub Action for OpenAI enriched Vale 
author: phoban01
branding:
  icon: check
  color: green

inputs:
  version:
    description: "The Vale CLI version to install."
    required: false
    default: "latest"

  path:
    description: "The input file to review."
    required: true
    default: ""

  debug:
    description: "Log debugging information to stdout."
    required: false
    default: "false"

  reporter:
    description: "Reporter of reviewdog command [github-pr-check,github-pr-review,github-pr-annotations,github-check]."
    required: false
    default: "github-pr-review"

  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    required: false
    default: "false"

  level:
    description: "Report level for reviewdog [info,warning,error]."
    required: false
    default: "error"

  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: "added"

  vale_ini_path:
    description: "Path to the vale configuration file."
    required: false
    default: ".github/.vale.ini"

  vale_flags:
    description: "Space-delimited list of flags for the Vale CLI."
    required: false
    default: ""

  separator:
    description: "Split character for input strings."
    required: false
    default: ""

  reviewdog_url:
    description: "The URL to a tar.gz build of reviewdog to use in the action"
    required: false
    default: ""

  token:
    description: "The GitHub token to use."
    required: false
    default: ${{ github.token }}

  openai_api_key:
    description: "The OpenAI API Key to use."
    required: true
    default: ""

runs:
  using: "node20"
  main: "lib/main.js"
